; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_h753zi]
platform = ststm32
board = nucleo_h753zi
framework = arduino
extra_scripts = pre:extra_script.py

build_flags =
    -D_FREE_RTOS
    -DXCPLIB_CFG_OVERRIDE=\"xcplib_rtos_cfg.h\"
    -DXCP_PROJECT_NAME=\"stm32_freertos_demo\"
    -DFASTTASK_SCOPE_PIN=LED_BUILTIN
    -DSLOWTASK_SCOPE_PIN=LED_BUILTIN

lib_deps =
    stm32duino/STM32duino FreeRTOS
    stm32duino/STM32duino LwIP
